backend:
  name: git-gateway
  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Título", name: "title", widget: "string"}
      - {label: "Data de publicação", name: "date", widget: "datetime"}
      - {label: "Identificador do youtube", name: "ytkey", widget: "string"}
      - {label: "Imagem de destaque", name: "featuredimage", widget: image}
      - {label: "Comentário sobre o vídeo", name: "body", widget: "markdown"}
      - {label: "Categorias", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Início"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: "Título da página", name: title, widget: string}
          - {label: "Imagem", name: image, widget: image}
          - {label: "Título destaque", name: heading, widget: string}
          - {label: "Sub-título destaque", name: subheading, widget: string}
          - {label: "Descrição", name: description, widget: string}
      - file: "src/pages/about/index.md"
        label: "Espaço LuzJo"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Título", name: "title", widget: "string"}
          - {label: "Corpo", name: "body", widget: "markdown"}
          - {label: "Imagem perfil", name: image, widget: image}
          - {label: "Mensagem perfil", name: imgdescription, widget: string}
